# Aliases
alias yt="yarn test"
alias yj="yarn jest --watch"
alias yju="yarn jest --u"
alias yf="yarn flow"
alias yl="yarn eslint ."
alias rn="react-native"
alias rna="react-native run-android"
alias rni='react-native run-ios --simulator="iPhone SE"'
alias ad="adb devices -l"
alias emu23="emulator -avd Nexus_5X_API_23 &"
alias emu="emulator -avd Nexus_6_API_26_1 &"
alias nvimrc="nvim ~/.config/nvim/init.vim"
alias nvimzshrc="nvim ~/.zshrc"
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias gti=git
alias ...="cd ../.."
alias ....="cd ../../.."
alias ngrok="~/.dotfiles/bin/ngrok"
alias cat="bat -p --paging=never"
alias pn="pnpm"
